Carpooling.MVC/Models/FeedbackViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Carpooling.Data.Models;

namespace Carpooling.MVC.Models
{
    public class FeedbackViewModel
    {
        public FeedbackViewModel()
        {

        }
        public FeedbackViewModel(Feedback feedback)
        {
            FeedbackId = feedback.Id;
            Rating = feedback.Rating;
            Comment = feedback.Description;
        }
        public Guid FeedbackId { get; set; }
        public Guid TripId { get; set; }
        [Required]
        public int Rating { get; set; }
        [MaxLength(200, ErrorMessage = "Comment length must be {1}!")]
        public string Comment { get; set; }
    }
}

Carpooling.MVC/Controllers/FeedbackController.cs
using System;
using System.Threading.Tasks;
using Carpooling.MVC.Models;
using Carpooling.Services;
using Carpooling.Services.Contracts;
using Carpooling.Services.DTO.IncomeDTOs;
using Carpooling.Services.Exceptions.Exeception.User;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Carpooling.MVC.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly ILoginService loginService;
        private readonly ModelMapper modelMapper;
        private readonly IFeedbackService feedbackService;
        private readonly ITripService tripService;
        public FeedbackController(ITripService tripService, IFeedbackService feedbackService, ILoginService loginService, ModelMapper modelMapper)
        {
            this.tripService = tripService;
            this.loginService = loginService;
            this.modelMapper = modelMapper;
            this.feedbackService = feedbackService;
        }

        public async Task<IActionResult> Index()
        {
            if(!this.Request.Cookies.ContainsKey("UserKey"))
            {
                return this.RedirectToAction("Login", "Auth");
            }

            var key = this.Request.Cookies["UserKey"];
            var userData = await this.loginService.CheckUsersPasswordKeyAsync(key);
            var userFeedbacks = await this.feedbackService.ListAllUserFeedbacksAsync(userData.Id);
            var foodbackView = this.modelMapper.ToFeedbackViewFromFeedback(userFeedbacks);

            return this.View("UserFeedbacks", foodbackView);
        }

        public async Task<IActionResult> FeedbackForMe()
        {
            if(!this.Request.Cookies.ContainsKey("UserKey"))
            {
                return this.RedirectToAction("Login", "Auth");
            }

            var key = this.Request.Cookies["UserKey"];
            var userData = await this.loginService.CheckUsersPasswordKeyAsync(key);
            var feedbackForUser = await this.feedbackService.ListAllFeedbacksForUserAsync(userData.Id);
            var foodbackView = this.modelMapper.ToFeedbackViewFromFeedback(feedbackForUser);

            return this.View("FeedbackForUser", foodbackView);
        }

        [ActionName("EditForm")]
        public async Task<IActionResult> Edit(Guid Id)
        {
            try
            {
                var feedback = await this.feedbackService.GetFeedbackAsync(Id);
                var feedbackView = new FeedbackViewModel(feedback);

                return this.View("Edit", feedbackView);
            }
            catch(FeedbackException ex)
            {
                this.ViewBag.Error = ex.Message;
                this.Response.StatusCode = StatusCodes.Status404NotFound;

                return this.View("Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(FeedbackViewModel feedbackViewModel)
        {
            if(!ModelState.IsValid)
            {
                return this.View(feedbackViewModel);
            }

            var feedback = this.modelMapper.ToFeedbackFromFeedbackViewModel(feedbackViewModel);
            await this.feedbackService.EditFeedbackAsync(feedback);

            return this.RedirectToAction("Index");
        }

        public IActionResult LeaveFeedbackForm(Guid Id)
        {
            if(!this.Request.Cookies.ContainsKey("UserKey"))
            {
                return this.RedirectToAction("Login", "Auth");
            }

            FeedbackViewModel commentData = new FeedbackViewModel();
            commentData.TripId = Id;

            return this.View("AddFeedback", commentData);
        }

        [HttpPost]
        public async Task<IActionResult> LeaveFeedback(FeedbackViewModel feedbackData)
        {
            if(!this.Request.Cookies.ContainsKey("UserKey"))
            {
                return this.RedirectToAction("Login", "Auth");
            }

            var key = this.Request.Cookies["UserKey"];

            try
            {
                var userData = await this.loginService.CheckUsersPasswordKeyAsync(key);
                var feedback = new CreateFeedbackDTO()
                {
                    Rating = feedbackData.Rating.ToString(),
                    Description = feedbackData.Comment,
                    TripId = feedbackData.TripId,
                    Username = userData.Username
                };

                var result = await this.feedbackService.CreateFeedbackAsync(feedback);

                return this.RedirectToAction("MyTrips", "Trip");
            }
            catch(EntityNotFound ex)
            {
                return this.BadRequest(ex.Message);
            }
        }
    }
}

Carpooling.MVC/Views/Feedback/AddFeedback.cshtml
@{ ViewBag.Title = "Add Trip Comment"; }
@model Carpooling.MVC.Models.FeedbackViewModel

<h2>Add Trip Comment</h2>
<form asp-controller="Feedback" asp-action="LeaveFeedback" asp-route-TripId="@Model.TripId">
    <label for="Text comment" class="form-label mt-4">Trip Rating</label>
    <div class="form-group">
        <label for="exampleSelect1" class="form-label mt-4">Select Rating</label>
        <select asp-for="@Model.Rating" class="form-select" id="exampleSelect1">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
    </div>
    <div class="form-group">
        <label for="Text comment" class="form-label mt-4"></label>
        <textarea asp-for="@Model.Comment" class="form-control" id="exampleTextarea" rows="3"></textarea>
    </div>
    <div>
        <button type="submit" class="btn btn-primary">Add Comment</button>
        <button asp-action="Index" type="submit" class="btn btn-primary">Back</button>
    </div>
</form>

Carpooling.MVC/Views/Feedback/Edit.cshtml
@{ ViewBag.Title = "Edit Trip Comment"; }
@model Carpooling.MVC.Models.FeedbackViewModel

<h2>Edit Trip Comment</h2>
<form asp-controller="Feedback" asp-action="Edit" asp-route-FeedbackId="@Model.FeedbackId">
    <label for="Text comment" class="form-label mt-4">Trip Rating</label>
    <div class="form-group">
        <label for="exampleSelect1" class="form-label mt-4">Select Rating</label>
        <select asp-for="@Model.Rating" class="form-select" id="exampleSelect1">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
    </div>
    <div class="form-group">
        <label for="Text comment" class="form-label mt-4"></label>
        <textarea asp-for="@Model.Comment" class="form-control" id="exampleTextarea" rows="3">@Model.Comment</textarea>
    </div>
    <div>
        <button type="submit" class="btn btn-primary">Edit Comment</button>
        <button asp-action="Index" type="submit" class="btn btn-primary">Back</button>
    </div>
</form>

Carpooling.MVC/Views/Feedback/FeedbackForUser.cshtml
@{ ViewBag.Title = "Feedback For Me"; }
@model ICollection<Carpooling.MVC.Models.FeedbackModel>

<h2>My Trips</h2>
<form asp-controller="Trip" asp-action="MyTrips" >
    <button type="submit" class="btn btn-primary">Back</button>
</form>
<br>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Rating </th>
            <th scope="col">Comment</th>
            <th scope="col">Driver/Passenger</th>
            <th scope="col">Trip Departure</th>
            <th scope="col">From - To</th>
        </tr>
    </thead>
    @{
        foreach(var comment in this.Model)
        {
            <tbody>
                <tr class="table-active">
                    <th scope="row">@comment.Rating</th>
                    <td>@comment.Description</td>
                    <td>@comment.Role</td>
                    <td>@comment.Departure</td>
                    <td>@comment.StartDestination - @comment.EndDestination</td>
                </tr>
            </tbody>
        }
    }
</table>

Carpooling.MVC/Views/Feedback/UserFeedbacks.cshtml
@{ ViewBag.Title = "My Feedback"; }
@model ICollection<Carpooling.MVC.Models.FeedbackModel>

<h2>My Trips</h2>
<form asp-controller="Trip" asp-action="MyTrips" >
    <button type="submit" class="btn btn-primary">Back</button>
</form>
<br>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Rating </th>
            <th scope="col">Comment</th>
            <th scope="col">Driver/Passenger</th>
            <th scope="col">Trip Departure</th>
            <th scope="col">From - To</th>
        </tr>
    </thead>
    @{
        foreach(var comment in this.Model)
        {
            <tbody>
                <tr class="table-active">
                    <th scope="row">@comment.Rating</th>
                    <td>@comment.Description</td>
                    <td>@comment.Role</td>
                    <td>@comment.Departure</td>
                    <td>@comment.StartDestination - @comment.EndDestination</td>
                    <td>
                        <form asp-controller="Feedback" asp-action="EditForm" asp-route-id="@comment.Id">
                            <button type="submit" class="btn btn-primary">Edit</button>
                        </form>
                    </td>
                </tr>
            </tbody>
        }
    }
</table>