Carpooling.MVC/Controllers/AuthController.cs
using System;
using System.Threading.Tasks;
using Carpooling.MVC.Models;
using Carpooling.Services.Contracts;
using Carpooling.Services.DTO.IncomeDTOs;
using Carpooling.Services.Exceptions.Exeception.User;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreDemo.Web.Controllers
{

    public class AuthController : Controller
    {
        private IUserService userServise;
        private ILoginService loginService;
        private UserDTO userDTO;
        private ModelMapper modelMapper;

        public AuthController(IUserService userServise, ILoginService loginService, UserDTO userDTO, ModelMapper modelMapper)
        {
            this.userServise = userServise;
            this.loginService = loginService;
            this.userDTO = userDTO;
            this.modelMapper = modelMapper;
        }

        //GET: /auth/login
        [ActionName("LoginForm")]
        public IActionResult Login()
        {
            var loginViewModel = new LoginViewModel();

            return this.View("Login", loginViewModel);
        }

        //POST: /auth/login
        [HttpPost]
        public async Task<IActionResult> Login([Bind("Username, Password")] LoginViewModel loginViewModel)
        {
            if(!this.ModelState.IsValid)
            {
                return this.View(loginViewModel);
            }
            try
            {
                var loginDTO = this.modelMapper.ToLoginDTO(loginViewModel);
                var userKey = await this.loginService.CheckUserCredentialsAsync(loginDTO);
                var userRole = await this.userServise.GetUserByUserNameAsync(loginViewModel.Username);
                var role = "User";
                if(userRole.IsAdmin)
                {
                    role = "Admin";
                }
                this.Response.Cookies.Append("UserKey", userKey);
                this.Response.Cookies.Append("UserRole", role);
                this.Response.Cookies.Append("UserName", userRole.Username);

                return this.RedirectToAction("Index", "Home");
            }
            catch(ArgumentException ex)
            {
                this.ModelState.AddModelError("Username", ex.Message);
                this.ModelState.AddModelError("Password", ex.Message);
            }
            catch(PasswordIncorrectException ex)
            {
                this.ModelState.AddModelError("Password", ex.Message);
            }

            return this.View(loginViewModel);
        }

        //GET: /auth/logout
        public IActionResult Logout()
        {
            this.Response.Cookies.Delete("UserKey");
            this.Response.Cookies.Delete("UserRole");
            this.Response.Cookies.Delete("UserName");

            return this.RedirectToAction("index", "home");
        }

        //GET: /auth/register
        [ActionName("RegisterForm")]
        public IActionResult Register()
        {
            var registerViewModel = new CreateViewModel();

            return this.View("Register", registerViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Register([Bind("Username, Password, PhoneNumber, FirstName ,LastName ,Email, ImageUrl")] CreateViewModel createViewModel)
        {
            if(!this.ModelState.IsValid)
            {
                return this.View(createViewModel);
            }

            try
            {
                var userDTO = this.modelMapper.ToUserDTO(createViewModel);
                var user = await this.userServise.CreateUserAsync(userDTO);

                return this.RedirectToAction("Index", "Home");
            }

            catch(ArgumentException ex)
            {
                this.ModelState.AddModelError("", ex.Message);
            }
            catch(UserNameExistException ex)
            {
                this.ModelState.AddModelError("Username", ex.Message);
            }
            catch(EmailIncorrectException ex)
            {
                this.ModelState.AddModelError("Email", ex.Message);
            }
            catch(EmailExistsException ex)
            {
                this.ModelState.AddModelError("Email", ex.Message);
            }
            catch(NudeAvatarException ex)
            {
                this.ModelState.AddModelError("ImageUrl", ex.Message);
            }

            return this.View(createViewModel);
        }
    }
}

Carpooling.MVC/Controllers/HomeController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Carpooling.MVC.Models;
using Carpooling.Services;
using Carpooling.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Carpooling.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IFeedbackService feedbackService;
        private readonly IUserService userService;
        private readonly ITripService tripService;

        public HomeController(ILogger<HomeController> logger, IFeedbackService feedbackService, IUserService userService, ITripService tripService)
        {
            _logger = logger;
            this.feedbackService = feedbackService;
            this.userService = userService;
            this.tripService = tripService;
        }

        public async Task<IActionResult> Index()
        {
            var users = await this.userService.GetAllUsersAsync();
            var trips = await this.tripService.GetAllTripsAsync();
            var feedbacks = await this.feedbackService.ListAllFeedbacksAsync();
            var ratings = await this.feedbackService.AllRatingsCountAsync();
            var ratingsAverage = ratings.Count() / feedbacks.Count();

            var tripsDTO = trips.Select(t => new TripDTO(t)).ToList();

            var homeModel = new HomePageViewModel()
            {
                Users = users,
                Trips = tripsDTO,
                Feedbacks = feedbacks,
                Ratings = ratings,
                AverageRating = ratingsAverage
            };

            return View(homeModel);
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactUsViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    using(MailMessage msz = new MailMessage())
                    {
                        msz.From = new MailAddress(viewModel.Email);

                        msz.To.Add("carpoolingtelerik@gmail.com");
                        msz.Subject = viewModel.Topic;
                        msz.Body = "From:  " + viewModel.Email + "\n\n" + "Phone Number:" + viewModel.PhoneNumber + "\n\n" + viewModel.Description;

                        SmtpClient smtp = new SmtpClient();

                        smtp.Host = "smtp.gmail.com";

                        smtp.Port = 587;

                        smtp.EnableSsl = true;


                        smtp.DeliveryMethod = SmtpDeliveryMethod.Network;

                        smtp.UseDefaultCredentials = false;

                        smtp.Credentials = new System.Net.NetworkCredential("carpoolingtelerik@gmail.com", "qhtenlak1");

                        smtp.Send(msz);

                        ModelState.Clear();
                        ViewBag.Message = "Thank you for getting in touch! ";
                    };
                }
                catch(Exception ex)
                {
                    ModelState.Clear();
                    ViewBag.Message = $"We are sorry, but there is a problem - {ex.Message}";
                }
            }

            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }

        //public IActionResult TopDrivers()
        //{
        //    var topDrivers = this.feedbackService.TopTenDirverPassengerRatings(Data.Enums.TravelRole.Driver);
        //    //var topDriversView = topDrivers.Select(td => td.ToTopCustomerViewModel()).ToArray();

        //    //return View(topDriversView); // TODO
        //     throw new NotImplementedException();

        //}
        //public IActionResult TopPassengers()
        //{
        //    var topPassengers = this.feedbackService.TopTenDirverPassengerRatings(Data.Enums.TravelRole.Passenger);
        //    //var topPassengersView = topPassengers.Select(td => td.ToTopCustomerViewModel()).ToArray();

        //    //return View(topPassengersView); // TODO
        //     throw new NotImplementedException();
        //}

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult PageNotFound()
        {
            return this.View();
        }
    }
}

Carpooling.MVC/Views/Home/About.cshtml
@{ ViewBag.Title = "About"; }

<div class="info-header mb-5 container mt-5">
    <h1 class="text-primary pb-3 about-title text-center">
        Why is Carpooling the best?
    </h1>
    <p class="lead pb-3 text-center">
        Carpooling is a web application that enables you to share your travel from one location to other with other passengers. Every user can either organize a shared travel or request to join someone else’s travel.
        Sharing a carpool is a great way to travel. It's affordable, comfortable and eco-friendly! The aim of Carpooling is to make travel buddy search easier, to increase the comfort of travelling, to reduce costs and last but not the least, to protect the environment.
    </p>
</div>

<div class="accordion container px-lg-5" id="accordionPanelsStayOpenExample">
    <div class="accordion-item">
        <h2 class="accordion-header" id="panelsStayOpen-headingOne">
            <p class="text-primary pb-3 about-title text-center"> Travel at а low price</p>
        </h2>
        <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
            <div class="accordion-body">
                <p class="lead pb-3 text-center">  No matter where you are going, there’s a carpooling ride that will get you there for less, while reducing CO2 emmissions.</p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
            <p class="text-primary pb-3 about-title text-center">Trustworthy and secure</p>
        </h2>
    </div>
    <div class="accordion-item">
        <div class="accordion-body">
            <p class="lead pb-3 text-center"> We take the time to get to know each of our members. We check reviews, profiles and IDs, 
            so you know who you’re travelling with and can book your ride at ease on our secure platform.</p>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="panelsStayOpen-headingThree">
            <p class="text-primary pb-3 about-title text-center"> Easy to book a ride </p>
        </h2>
    </div>
    <div class="accordion-item">
        <div class="accordion-body">
            <p class="lead pb-3 text-center">There is always a ride close to you, just apply for the nearest trip and if the driver approves you then you are ready to go.</p>
        </div>
    </div>
</div>

Carpooling.MVC/Views/Home/Contact.cshtml
@{ ViewData["Title"] = "Contacts"; }

<body class="theme-1">
    <div class="breadcrumb-div">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                </div>
                <div class="col-6">
                </div>
            </div>
        </div>
    </div>
    <div class="div-padding contact-info-div">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 offset-lg-0 col-sm-6 offset-sm-3">
                    <div class="single-contact-info text-center">
                        <h4>Our E-mail</h4>
                        <p>carpoolingtelerik@gmail.com</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single-contact-info text-center">
                        <h4>Our meeting spot</h4>
                        <p>Vasil Aprilov 66, Plovdiv, Bulgaria</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single-contact-info text-center">
                        <h4>Our phone numbers</h4>
                        <p>Stanimir: +359899279132, Stanislav: +359895196358</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="div-padding contact-form-div p-t-0">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <partial name="_ContactUsFormPartial.cshtml" />
                </div>
                <div class="col-lg-6">
                    <div class="mapouter" style="float: right;">
                        <div class="gmap_canvas">
                            <iframe width="500" height="600" id="gmap_canvas"
                                    src="https://maps.google.com/maps?q=free%20bar&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                    frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
                            </iframe>
                            <style>
                                .mapouter {
                                    position: relative;
                                    text-align: right;
                                    height: 500px;
                                    width: 600px;
                                }
                            </style><a href="https://www.embedgooglemap.net"></a>
                            <style>
                                .gmap_canvas {
                                    overflow: hidden;
                                    background: none !important;
                                    height: 500px;
                                    width: 600px;
                                }
                            </style></div></div>
                            <style>
                                .mapouter {
                                    position: relative;
                                    text-align: right;
                                    height: 620px;
                                    width: 550px;
                                }
                            </style>
                            <style>
                                .gmap_canvas {
                                    overflow: hidden;
                                    background: none !important;
                                    height: 620px;
                                    width: 550px;
                                }
                            </style>
                        </div>
                    </div>
                </div>
            </div>
</body>

Carpooling.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home"
;}

@{ this.ViewData["IsAuthenticated"] = this.Context.Request.Cookies.ContainsKey("UserKey");
    this.ViewData["CurrentUserRole"] = this.Context.Request.Cookies["UserRole"]; }

@model Carpooling.MVC.Models.HomePageViewModel

<!DOCTYPE html>
<div class="text-center">

    <section id="firstPage">

        <div class="container position-relative">
            <div class="text-center">
                <h1 class="mb-4 display-1 lh-sm text-center">Don't travel alone!<br class="d-block d-lg-none d-xl-block" />Find your travel buddy now!</h1>
                <p class="mt-4 mb-5 fs-1 lh-base text-center">Join other like-minded people in saving money and the planet by car sharing</p>
                @if(!(bool)this.ViewData["IsAuthenticated"])
                {
                    <a class="btn btn-lg btn-primary hover-top" asp-controller="Auth" asp-action="RegisterForm" role="button">Register Now</a>
                }
                else
                {
                    <a class="btn btn-lg btn-primary hover-top" asp-controller="Trip" asp-action="Index" role="button">Available Trips</a>

                }
            </div>
        </div>

    </section>
    <br>
    <div class="row">
        <div class="col">
            <img src="~/assets/defaultImage/signUp.png" alt="">
            <div class="how-work-text">
                <h4>Register For Free</h4>
                <p>Drivers and passengers don’t pay any registration or membership fee. Everything is free, because our aim is to make traveling accessible to everybody!</p>
            </div>
        </div>
        <div class="col">

            <img src="~/assets/defaultImage/dailyTrips.png" alt="">
            <div class="how-work-text">
                <h4>Daily Trips</h4>
                <p>Find a carpool buddy for your daily commute at no cost and even make a schedule so you can travel frequently together!</p>
            </div>
        </div>
        <div class="col">
            <img src="~/assets/defaultImage/longDistance.png" alt="">
            <div class="how-work-text">
                <h4>Long Distance Trips</h4>
                <p>Post or book a ride everywhere in Еurope. Both short and long distance destinations are available!</p>
            </div>
        </div>
    </div>
    <section id="numbers">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-3 no-padding text-center num d-flex flex-column">
                    <i class="fa fa-user"></i>
                    <h3 class='font-weight-bold' data-min='0' data-max='' data-delay='5' data-increment='1'>@Model.Users.Count()</h3>
                    <h4>Users</h4>

                </div>
                <div class="col-sm-6 col-md-6 col-lg-3 no-padding text-center num d-flex flex-column">
                    <i class="fa fa-car-side"></i>
                    <h3 class='font-weight-bold' data-min='0' data-max='@Model.Trips.Count()' data-delay='4' data-increment='1'>@Model.Trips.Count()</h3>
                    <h3>Trips</h3>

                </div>
                <div class="col-sm-6 col-md-6 col-lg-3 no-padding text-center num d-flex flex-column">
                    <i class="fa fa-car-side"></i>
                    <h3 class='font-weight-bold' data-min='0' data-max='@Model.Feedbacks.Count()' data-delay='4' data-increment='1'>@Model.Feedbacks.Count()</h3>
                    <h3>Feedbacks</h3>

                </div>
                <div class="col-sm-6 col-md-6 col-lg-3 no-padding text-center num d-flex flex-column">
                    <i class="fa fa-car-side"></i>
                    <h3 class='font-weight-bold' data-min='0' data-max='@Model.AverageRating' data-delay='4' data-increment='1'>@Model.AverageRating</h3>
                    <h3>Average Rating</h3>

                </div>
            </div>
        </div>
    </section>
    <section class="pt-5" id="featuresVideos">
        <div class="container">
            <div class="row flex-center">
                <div class="col-12">
                    <div class="carousel slide" id="carouselExampleIndicators" data-bs-touch="false" data-bs-interval="false">
                        <div class="row align-items-center">
                            <div class="col-12 col-xxl-7 px-2">
                                <div class="carousel-inner">
                                    <div class="carousel-item active h-100">
                                        <div id="player" class="player" data-plyr-provider="youtube" data-plyr-embed-id="bTqVqk7FSmY">
                                            <iframe width="560" height="315" src="https://www.youtube.com/embed/-LQtdKgipPI" title="YouTube video player" frameborder="0" allow="accelerometer;
                                                autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Carpooling.MVC/Views/Home/PageNotFound.cshtml
@{
    this.Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/x-icon" href="../assets/images/favicon/favicon.ico">
    <link rel="stylesheet" href="~/lib/prismjs/themes/prism.css">
    <link rel="stylesheet" href="~/lib/prismjs/plugins/line-numbers/prism-line-numbers.css">
    <link rel="stylesheet" href="~/lib/prismjs/plugins/toolbar/prism-toolbar.css">
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/dropzone/dist/dropzone.css">
    <link href="~/lib/mdi/font/css/materialdesignicons.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.css">
    <link rel="stylesheet" href="~/css/theme.min.css">
    <title>404 error</title>
</head>

<body>
    <div class="container min-vh-100 d-flex justify-content-center
      align-items-center">
        <div class="row">
            <div class="col-12">
                <div class="text-center">
                    <div class="mb-3">
                        <img src="~/images/error/404-error-img.png" alt="" class="img-fluid">
                    </div>
                    <h1 class="display-4 fw-bold">Oops! the page not found.</h1>
                    <p class="mb-4"> Or simply leverage the expertise of our consultation team. </p>
                    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Go Home</a>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/lib/feather-icons/dist/feather.min.js"></script>
    <script src="~/lib/prismjs/components/prism-core.min.js"></script>
    <script src="~/lib/prismjs/components/prism-markup.min.js"></script>
    <script src="~/lib/prismjs/plugins/line-numbers/prism-line-numbers.min.js"></script>
    <script src="~/lib/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/lib/dropzone/dist/min/dropzone.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.12/clipboard.min.js"></script>
    <script src="~/js/theme.min.js"></script>
</body>
</html>

Carpooling.MVC/Views/Home/_ContactUsFormPartial.cshtml
@model Carpooling.MVC.Models.ContactUsViewModel


@if(ViewBag.Message == null)
{
    <div class="row" style="padding: 30px; background-color: #F7F7F6;">

        <form method="post">
            <h2>Send Email</h2>
            <div class="row">

                <div class="col-lg-6">
                    <span asp-validation-for="Name" class="form-error"></span>
                    <div class="form-group">
                        <label asp-for="Name">Full Name</label>
                        <input asp-for="Name" class="form-control" />
                    </div>
                </div>
                <div class="col-lg-6">
                    <span asp-validation-for="Email" class="form-error"></span>
                    <div class="form-group">
                        <label asp-for="Email">Email</label>
                        <input asp-for="Email" class="form-control" />
                    </div>
                </div>
                <div class="col-lg-6">
                    <span asp-validation-for="PhoneNumber" class="form-error"></span>
                    <div class="form-group">
                        <label asp-for="PhoneNumber">Phone Number</label>
                        <input asp-for="PhoneNumber" class="form-control" />
                    </div>
                </div>
                <div class="col-lg-6">
                    <span asp-validation-for="Topic" class="form-error"></span>
                    <div class="form-group">
                        <label asp-for="Topic">Topic</label>
                        <input asp-for="Topic" class="form-control" />
                    </div>
                </div>
                <div class="col-lg-12">
                    <span asp-validation-for="Description" class="form-error"></span>
                    <div class="form-group">
                        <label asp-for="Description">Description</label>
                        <textarea rows="5" cols="15"
                                  asp-for="Description" class="form-control"></textarea>
                    </div>
                </div>

                <div class="col-lg-12">
                    <button type="submit"
                            class="btn btn-primary">
                        Send
                    </button>
                </div>

            </div>
        </form>
    </div>}

<div>
    <div>
        @if(ViewBag.Message != null)
        {
            <div class="fs-4" style="text-align: center">@ViewBag.Message</div>}
    </div>
</div>